### ISSUE TITLE
Grocy reverse proxy Traefik

### ISSUE THREAD

**Issue by madereddy** [linuxserver/docker-grocy#10]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Ubuntu 18.10

version: "2"
services:
  grocy:
    image: linuxserver/grocy
    container_name: grocy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /disk2/grocy:/config
    ports:
      - 9283:80
    restart: unless-stopped
    networks:
      - monitoring
    labels:
      - "traefik.enable=true"
      - "traefik.backend=grocy"
      - "traefik.frontend.rule=Host:EXAMPLE.com; PathPrefix: /grocy;"
      - "traefik.port=80"
      - "traefik.protocol=http"

networks:
  monitoring:
   external:
    name: monitoring

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.

[s6-init] ensuring user provided files have correct perms...exited 0.

[fix-attrs.d] applying ownership & permissions fixes...

[fix-attrs.d] done.

[cont-init.d] executing container initialization scripts...

[cont-init.d] 10-adduser: executing... 

-------------------------------------

          _         ()

         | |  ___   _    __

         | | / __| | |  /  \ 

         | | \__ \ | | | () |

         |_| |___/ |_|  \__/

Brought to you by linuxserver.io

We gratefully accept donations at:

https://www.linuxserver.io/donate/

-------------------------------------

GID/UID

-------------------------------------

User uid:    1000

User gid:    1000

-------------------------------------

[cont-init.d] 10-adduser: exited 0.

[cont-init.d] 20-config: executing... 

[cont-init.d] 20-config: exited 0.

[cont-init.d] 30-keygen: executing... 

using keys found in /config/keys

[cont-init.d] 30-keygen: exited 0.

[cont-init.d] 50-config: executing... 

[cont-init.d] 50-config: exited 0.

[cont-init.d] 99-custom-files: executing... 

[custom-init] no custom files found exiting...

[cont-init.d] 99-custom-files: exited 0.

[cont-init.d] done.

[services.d] starting services

[services.d] done.

NA

Essentially I am unable to get Grocy to work as a subdirectory. I got Ombi and Tautulli from you guys working as a subdirectory so I dont know what is causing this issue with same label setup.

**Comment by KeirDavis1** [comment]
Above also worked for me

In docker-compose.yml

```
...
 grocy:
    ...
    labels:
      traefik.enable: "true"
      traefik.port: "80"
      traefik.protocol: http
      traefik.frontend.rule: "Host:10.25.0.20; PathPrefixStrip: /grocy"
      traefik.backend: "grocy"
```

Then in grocy's data/config.php

```
Setting('BASE_URL', 'http://[domain]/grocy');
```

Like a charm! Thanks madereddy
