### ISSUE TITLE
Grocy not configurable with Environment Variables

### ISSUE THREAD

**Issue by JoschaMiddendorf** [linuxserver/docker-grocy#12]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

UnRaid

![Bildschirmfoto 2019-07-04 um 00 17 33](https://user-images.githubusercontent.com/19818109/60628327-47df3380-9df1-11e9-918d-81a13788e883.png)

The grocy application can be configured by Environmetnt variables, seeconfig.php.

> An environment variable with the same name as the setting and prefix "GROCY_"

> so for example "GROCY_BASE_URL"

That doesn't work with this container, see screensot above.

**Comment by BastienVH** [comment]
Apparently the [official grocy docker](https://github.com/grocy/grocy-docker) container should be able to use the GROCY_CULTURE env variable to set language, but the container is a few months old now and I can't get it to start up properly on my OpenMediaVault install.
Is there something of use in that repo that could help enable env variables in the linuxserver/grocy repo?

**Comment by mrask90** [comment]
Would be nice to be able to change the language, when Grocy supports it.

**Comment by notDavid** [comment]
@mrask90 fyi you can already change the language, after starting the container go to the `config` folder on the host and open `config/data/config.php` to change the `CULTURE` setting.
Then stop/start the container.

**Comment by mrask90** [comment]
> @mrask90 fyi you can already change the language, after starting the container go to the `config` folder on the host and open `config/data/config.php` to change the `CULTURE` setting.
> Then stop/start the container.

Thanks!

**Comment by samirerraji** [comment]
Environment variable seems to work ok with my fresh install on hassio.

**Comment by hanzZzZzZ** [comment]
I had to add `clear_env = no` under the `[www]` pool section in `/config/php/www2.conf`, otherwise environment variables from Docker are not visible in PHP FPM processes

**Comment by homerr** [comment]
This seems quite niche with little work arounds, the general configuration of the container works OK so I'll close this one out. If somebody has suggestions on how the functionality could/should be modified, a new issue should be opened with the desired outcomes.

**Comment by Germs2004** [comment]
Can this problem be fixed in the docker image by including the `clear_env = no` code that hanzZzZzZ provided?  Adding that one line to my www2 file fixed this problem for me too, so I think LinuxServer/Grocy should include it in everyone's www2 file by default.

**Comment by jamesanderson9182** [comment]
> clear_env = no

I tried this and it worked. Perhaps one to add to documenation if new installs don't have this setting automatially. I needed this to set a lot of feature flag settings.

**Comment by jamesanderson9182** [comment]
> I had to add `clear_env = no` under the `[www]` pool section in `/config/php/www2.conf`, otherwise environment variables from Docker are not visible in PHP FPM processes

I tried this and it worked. Perhaps one to add to documenation if new installs don't have this setting automatially. I needed this to set a lot of feature flag settings.
