### ISSUE TITLE
Backup Grocy Data

### ISSUE THREAD

**Issue by JunkyardCat** [linuxserver/docker-grocy#16]
How do i backup grocy data? I just want to copy over my data from one server to another
Thanks

**Comment by lyz-code** [comment]
All data is stored in the `/config` directory, if you've mounted a volume there, you should be able to copy it to the new location

**Comment by JunkyardCat** [comment]
@lyz-code 
Thanks. Does the config path also contain the images? Im using linuxserver docker image not sure if thats has any effect?

**Comment by lyz-code** [comment]
Nope, the docker image is not stored into the config path directory. 

If you want to backup a specific version you can either save the git repository where the Dockerfile is defined, or do a `docker pull` of that specific version in another machine so you can do a push to a docker repository in case the linuxserver people decide to remove that specific version from their dockerhub account.

**Comment by dieselman8228** [comment]
I have Backups from a windows version of grocy is it possible to transfer them to Linux. they are just the inventory and barcode buddy backups?

**Comment by homerr** [comment]
Probably, this isn't where you'll get this answer I'm afraid you'll probably be best asking in their subreddit if this is possible... in theory it should be if the files are the same (and I imagine they are)

**Comment by ohare93** [comment]
> All data is stored in the `/config` directory, if you've mounted a volume there, you should be able to copy it to the new location

Where exactly is this config folder?
