### ISSUE TITLE
docker-grocy won't serve UI when running on a Raspberry Pi

### ISSUE THREAD

**Issue by KrishanBhasin** [linuxserver/docker-grocy#17]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
After installing the latest Rasbpian release, updating, installing docker & required dependencies, pulling the image & running it, Grocy should be viewable on port `9283`

## Current Behavior
After installing the latest Rasbpian release, updating, installing docker & required dependencies, pulling the image & running it, nothing is served on any exposed port (even after selecting different ones)

```
> curl localhost:9283
curl: (52) Empty reply from server
```
I pulled and ran a couple of webserver "hello world" images, and they served correctly, so it is not a networking issue.

## Steps to Reproduce

1. Install latest Raspbian on a raspberry pi
2. `sudo apt update && sudo apt upgrade`
3. `curl -sSL https://get.docker.com | sh`
4.  `sudo usermod -aG docker pi`
5. reboot the raspberry pi
6. run the docker container: 
```
docker create \
  --name=grocy \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=London \
  -p 9283:80 \
  -v ./data:/config \
  --restart unless-stopped \
  linuxserver/grocy
```

## Environment
**OS:**      Raspbian Buster Lite
**CPU architecture:** arm64      
**How docker service was installed:**      See "steps to reproduce" above

## Command used to create docker container (run/create/compose/screenshot)
 See "steps to reproduce" above

## Docker logs

```
Creating network "grocy-linux-docker_default" with the default driver
Creating grocy ... done                                                                                                 Attaching to grocy
grocy    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
grocy    | [s6-init] ensuring user provided files have correct perms...exited 0.
grocy    | [fix-attrs.d] applying ownership & permissions fixes...
grocy    | [fix-attrs.d] done.
grocy    | [cont-init.d] executing container initialization scripts...
grocy    | [cont-init.d] 01-envfile: executing...
grocy    | [cont-init.d] 01-envfile: exited 267.
grocy    | [cont-init.d] 10-adduser: executing...
grocy    | [cont-init.d] 10-adduser: exited 267.
grocy    | [cont-init.d] 20-config: executing...
grocy    | [cont-init.d] 20-config: exited 267.
grocy    | [cont-init.d] 30-keygen: executing...
grocy    | [cont-init.d] 30-keygen: exited 267.
grocy    | [cont-init.d] 50-config: executing...
grocy    | [cont-init.d] 50-config: exited 267.
grocy    | [cont-init.d] 99-custom-files: executing...
grocy    | [cont-init.d] 99-custom-files: exited 267.
grocy    | [cont-init.d] done.
grocy    | [services.d] starting services
grocy    | [services.d] done.
```

**Comment by KrishanBhasin** [comment]
It looks like its because I'm trying to run it on a Raspberry Pi Zero, which doesn't have a supported CPU

**Comment by aptalca** [comment]
That's right, rpi0 is armv6, our images require armv7 or higher.
