### ISSUE TITLE
Version 3.0.0 missing php7-ctype package

### ISSUE THREAD

**Issue by osuka** [linuxserver/docker-grocy#26]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

The latest version needs a dependency that is not present (php7-ctype). Otherwise errors pop up during normal operations.
------------------------------

## Expected Behavior
Should work with no errors displayed.

## Current Behavior
Complains with a red error popup on screen when browsing. Logs on the browser js console too.

## Steps to Reproduce
1. This is a straightforward error. Just using the application normally will trigger the error in /stockoverview

> The fix is to simply add `php7-ctype` to the Dockerfiles
> It can be fixed in a running container by opening a terminal session inside an running `apk update; apk add php7-ctype`. 

## Environment
**OS:** Linux
**CPU architecture:** x86_64
**How docker service was installed:** Synology launch

## Command used to create docker container (run/create/compose/screenshot)
Standard docker run command from latest.

## Docker logs
Nothing shown on docker logs regarding this error.

**Comment by Forceu** [comment]
Temporary fix until the PR is merged:

Execute `docker exec -it YOUR_CONTAINER_NAME apk add php7-ctype` and restart the container

**Comment by aptalca** [comment]
fixed in #27
