### ISSUE TITLE
Nightly Builds with latest commits in main repo

### ISSUE THREAD

**Issue by PotentialIngenuity** [linuxserver/docker-grocy#29]
I reported a bug on the main repo and it was fixed accordingly. I would like to use the fix and am willing to accept the risk of running new code.

**Comment by Typositoire** [comment]
Is the nightly thing a possibility ?

**Comment by homerr** [comment]
We don't tend to produce nightly builds for containers, they are quite intensive on the build process and can lead some users down a broken path. So I'm afraid on this occasion the answer is no.
