### ISSUE TITLE
Image is not starting - can't find crt key

### ISSUE THREAD

**Issue by DonPavlov** [linuxserver/docker-grocy#37]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
The image starts, webserver is reachable

## Current Behavior
The image is executed, started, but nothing happens. Webserver not reachable.
Installed on a Raspberry Pi 3.

## Steps to Reproduce

1. Use pi 3
2. Start image
3. Wait
4. Nothing happens on webport.

## Environment
Raspbian 
armv7
Pi 3

## Command used to create docker container (run/create/compose/screenshot)
docker run -d   --name=grocy   -e PUID=1000   -e PGID=1000   -e TZ=Europe/Berlin   -p 9283:80   -v /home/pi/grocy:/config   --restart unless-stopped   ghcr.io/linuxserver/grocy

## Docker logs
https://pastebin.com/UNLKDm7N

**Comment by Roxedus** [comment]
Look at line 11-19 in your log.

**Comment by DonPavlov** [comment]
Thanks that fixed it. Startup still took something like 10 minutes but it works now.
