### ISSUE TITLE
problems with PHP timezone settings

### ISSUE THREAD

**Issue by alemoh1234** [linuxserver/docker-grocy#38]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
All should work as usual.

## Current Behavior
After some time working with the incorrect timezone(1 month working perfectely), the whole thing just gave up, at first it manifested as 504 error, but after fixing that, it shows the same error in other places, as well as an anomaly on nginx logs, perhaps indicating an even deeper problem, so there seems to be 2 problems.

## Steps to Reproduce
I could not get it to work, so basically, just download the container and run it, and you should already see errors relating to problem 1, that is the PHP timezone problem.

## Environment
**OS:** Raspbian GNU/Linux 10 (buster) armv7l
**CPU architecture:** arm32
**How docker service was installed:**
Just followed the guide on the README using compose

## Command used to create docker container (run/create/compose/screenshot)
![image](https://user-images.githubusercontent.com/10033854/110966090-b0571580-8333-11eb-9059-4d643c638cde.png)

## Docker logs
`----------------------------------

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

Your DockerHost is most likely running an outdated version of libseccomp

To fix this, please visit https://docs.linuxserver.io/faq#libseccomp

Some apps might not behave correctly without this

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 50-config: executing...
[cont-init.d] 50-config: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
`

So now as to what happens, after 1 month of it working fine I am greeted with this:
![image](https://user-images.githubusercontent.com/10033854/110963668-1db57700-8331-11eb-9a45-c55264b92c0e.png)

After looking at the logs, first I realized that nginx log date is 2037???(no ideia if this is a cause of the problem, system date is correct, and I didn`t touch any setting relating to this, nor could I find out how to fix it, important detail, I'am a noob in PHP and nginx) but then I realize, that the timezone value for PHP is for some reason reading the <> as well, something that left me even more confused, because I just followed the docker compose example on the README, that seems to be wrong.
![image](https://user-images.githubusercontent.com/10033854/110964205-b5b36080-8331-11eb-9b4d-46bf28ac5a74.png)

The operation timeout errors appeared afterwards, when the log date had gone crazy, after my first fix detailed bellow.

In any case, a proceeded to fix the timezone, changing this:
![image](https://user-images.githubusercontent.com/10033854/110964407-ea271c80-8331-11eb-8731-1f7e1da9a550.png)

To this:
![image](https://user-images.githubusercontent.com/10033854/110964461-fa3efc00-8331-11eb-8048-cde2838c2fcd.png)

and after restarting the container, that fixed this problem, and now I could log into the grocy webpage, but to my dismay, my headache wasn't over yet.

because now I can see the stock, but if I try to do anything, I get this:
![image](https://user-images.githubusercontent.com/10033854/110965027-949f3f80-8332-11eb-9729-88a73c3f3d7e.png)
and this
![image](https://user-images.githubusercontent.com/10033854/110965061-9e28a780-8332-11eb-96ca-a8e6121c33db.png)

And then everything seems to break, bug out and not work, So if anyone can help me out here, I will be ever so grateful , because after spending some good hours on this, I couldn't get any further.
nginx log now looks like this:
![image](https://user-images.githubusercontent.com/10033854/110965408-eb0c7e00-8332-11eb-8079-022ad402932f.png)

and PHP logs does not say a thing:
![image](https://user-images.githubusercontent.com/10033854/110965479-feb7e480-8332-11eb-89b6-c76eb9ef11c5.png)

Now to end it all, I thing there is a bug with docker compose when declaring the timezone, that is the first problem, and that somehow broke my installation causing a secondary problem, I tried updated and recreating the container, but to no avail, I hope this can be fixed.

**Comment by aptalca** [comment]
Multiple issues there

1. Your log tells you about the libseccomp problem in a huge banner, pay attention to it
2. Remove the bracket from the timezone setting

**Comment by alemoh1234** [comment]
I removed the brackets, but they were auto-generated by docker (as I understand it), and anyone using this container would face the same problem.

As for libseccomp I have no idea what it is, and this is my first experience with docker, and I chose it exactly because I have no experience with any of this, so if you could guide me as to what to do, I think it would be better, because I'am really lost here.

**Comment by alemoh1234** [comment]
Well, problem solved:
![image](https://user-images.githubusercontent.com/10033854/110968856-cadebe00-8336-11eb-895b-894533795b7c.png)

now as for the timezone problem I stumbled upon, should this get changed in the compose file?

**Comment by aptalca** [comment]
remove the brackets from your compose yaml

**Comment by alemoh1234** [comment]
I get that, but I meant fixing it for everyone, not just for me.

**Comment by aptalca** [comment]
brackets mean `variable` as in something you need to replace. You're supposed to take out the brackets when you replace it, just like when you did with the ` <path to data>` for the volume

**Comment by alemoh1234** [comment]
Understood, I thought it was some obscure PHP sintax (I hate PHP), thinking back the data path format was obvious to me, and that's why I changed it without thinking twice.

In any case, thank you very much for your help, I did not know about the docker log before today, guess I got a lot to learn hahaha.
