### ISSUE TITLE
Phone Camera not working as Barcode reader

### ISSUE THREAD

**Issue by mattexpa** [linuxserver/docker-grocy#41]
Hello there,

Is it just me or does the usage of the phone camera as Barcode scanner not working in this Docker version?

Tried it out on berrnds live demo and it worked out just fine but not on my locally hosted Docker one.

**Comment by murmelbahn** [comment]
Hi all,

I have the same issue. When I take a look at the browser console I see the following error:

enumerateDevices is not defined. This may mean that the user has declined camera access, or the browser does not support media APIs. If you are running in iOS, you must use Safari.

**Comment by homerr** [comment]
I'll take this away and test to see if I can get the error to reproduce.

**Comment by homerr** [comment]
Just looked at this and it is SSL related. Mapped 9284 to 443 on the container just to test (with it's self signed cert) and it does prompt for camera access. This message also comes up;

![image](https://user-images.githubusercontent.com/19776252/128609526-eb076cc9-bfa0-4f60-8adf-a310241a67c5.png)

Stick it behind a reverse proxy, or configure the SSL in the container properly and you'll be golden.
