### ISSUE TITLE
issue in running on arm64 ubuntu

### ISSUE THREAD

**Issue by travelg** [linuxserver/docker-grocy#44]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Using example docker file app should run

## Current Behavior

App loading goes to waiting state and then timeout in browser

## Steps to Reproduce

1. Run the example docker-compose given in introduction
2. wait untill app is started in docker logs
3. open in broswer with ip and port
4. broswer shows loading but after sometime timeout happens.

## Environment
**OS:** ubuntu server arm64
**CPU architecture:** arm64
**How docker service was installed:** from distro repo

## Command used to create docker container (run/create/compose/screenshot)

docker-compose up

## Docker logs

docker-compose up
Creating network "grocy-docker_default" with the default driver
Creating grocy ... done
Attaching to grocy
grocy          | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
grocy          | [s6-init] ensuring user provided files have correct perms...exited 0.
grocy          | [fix-attrs.d] applying ownership & permissions fixes...
grocy          | [fix-attrs.d] done.
grocy          | [cont-init.d] executing container initialization scripts...
grocy          | [cont-init.d] 01-envfile: executing... 
grocy          | [cont-init.d] 01-envfile: exited 0.
grocy          | [cont-init.d] 10-adduser: executing... 
grocy          | 
grocy          | -------------------------------------
grocy          |           _         ()
grocy          |          | |  ___   _    __
grocy          |          | | / __| | |  /  \ 
grocy          |          | | \__ \ | | | () |
grocy          |          |_| |___/ |_|  \__/
grocy          | 
grocy          | 
grocy          | Brought to you by linuxserver.io
grocy          | -------------------------------------
grocy          | 
grocy          | To support LSIO projects visit:
grocy          | https://www.linuxserver.io/donate/
grocy          | -------------------------------------
grocy          | GID/UID
grocy          | -------------------------------------
grocy          | 
grocy          | User uid:    1001
grocy          | User gid:    1001
grocy          | -------------------------------------
grocy          | 
grocy          | [cont-init.d] 10-adduser: exited 0.
grocy          | [cont-init.d] 20-config: executing... 
grocy          | [cont-init.d] 20-config: exited 0.
grocy          | [cont-init.d] 30-keygen: executing... 
grocy          | generating self-signed keys in /config/keys, you can replace these with your own keys if required
grocy          | Generating a RSA private key
grocy          | ....................................+++++
grocy          | ...+++++
grocy          | writing new private key to '/config/keys/cert.key'
grocy          | -----
grocy          | [cont-init.d] 30-keygen: exited 0.
grocy          | [cont-init.d] 50-config: executing... 
grocy          | [cont-init.d] 50-config: exited 0.
grocy          | [cont-init.d] 99-custom-files: executing... 
grocy          | [custom-init] no custom files found exiting...
grocy          | [cont-init.d] 99-custom-files: exited 0.
grocy          | [cont-init.d] done.
grocy          | [services.d] starting services
grocy          | [services.d] done.

## Log from /config/log/nginx/error.log
[error] 348#348: *3 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 192.168.1.10, server: _, request: "GET / 

## Log from /config/log/php/error.log
fpm is running, pid 328
NOTICE: ready to handle connections
WARNING: [pool www] server reached pm.max_children setting (5), consider raising it

**Comment by Roxedus** [comment]
> Command used to create docker container (run/create/compose/screenshot)

We want the actual compose you used

**Comment by travelg** [comment]
@Roxedus Thanks for quick reply, I was debugging. and found the issue. 

Issue is when I mount a data folder from network drive then timeout happens while loading a page.

Its strange as its 1 gbps connection and all other docker images works completely fine.

Do you have any suggestions how can I fix this mounting volume folder on a network drive. thanks

**Comment by Roxedus** [comment]
We do not recommend, or support having the /config mount on a network drive for any of our containers.

**Comment by travelg** [comment]
Ok. Thanks
