### ISSUE TITLE
unable to upload image for recipes 

### ISSUE THREAD

**Issue by ghvader** [linuxserver/docker-grocy#45]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
image should upload

## Current Behavior
errors out, never uploads

## Steps to Reproduce
1. create/upload recipe (works)
2. edit recipe (works)
3. click image, upload image, (fails)

## Environment
**OS:**
debian 10
**CPU architecture:** x86_64/arm32/arm64
x86_64
**How docker service was installed:**
via portainer, image deploys and runs

## Docker logs
2021/07/01 23:09:56 [error] 368#368: *34 FastCGI sent in stderr: "PHP message: PHP Notice:  Trying to get property 'picture_file_name' of non-object in /config/data/viewcache/80b12845534a6a50d9ab41bd668060c18bfd40ac.php on line 311" while reading response header from upstream, client: 192.168.2.26, server: _, request: "GET /recipe/new HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.3.5", referrer: "http://192.168.3.5/recipes"

**Comment by tobbenb** [comment]
Please post all info and full logs, not only snippets.

**Comment by ghvader** [comment]
@tobbenb I figured out the issue. posting in case it helps anyone else out.
there wasn't much in the logs, the only relevant line was what I posted above.
the issue ended up being the photo I was trying to upload was apparently to large.
it was 720x720 100k. after trying a ton of other things, I resized the photo to 180x180 22k and it upload right away. 
closing the issue.

**Comment by B1ue-W01f** [comment]
This isnt resolved, images shouldnt have to be restricted to such small file sizes without a decision by the developers to do so.

I haven't identified the issue but it appears to be solely restricted to this docker image - I'm presuming something related to the NGINX config.
