### ISSUE TITLE
Unable to Upload Images of Reasonable File Size

### ISSUE THREAD

**Issue by B1ue-W01f** [linuxserver/docker-grocy#57]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Uploading images of varying sizes to recipes from 2KB to 4MB. All files should upload.

## Current Behavior
On saving a recipe images should be uploaded and saved. Currently files above approx 100KB do not upload, this was not the intention of the app developers, resulting in the application hanging without understandable feedback.

## Steps to Reproduce
1. Deploy app
2. Upload image below 10KB, upload works
3. Upload image above 100KB, upload fails

## Environment
**OS: Kubernetes**
**CPU architecture:** x86_64
**How docker service was installed:**
Kubernetes manifest.

## Docker logs
No relevant logs

**Comment by B1ue-W01f** [comment]
See issue #45 too

**Comment by B1ue-W01f** [comment]
This should remain open, at least to help others fault find.

**Comment by homerr** [comment]
Cannot replicate issue with image uploads, suspect problem with any reverse proxy that may be in front of grocy.

**Comment by B1ue-W01f** [comment]
I think the issue was due to flannel CNI issues with vlan network. Reverse proxy was correct but migrating to calico CNI resolved the issue.

Just adding in case any one else ends up in the same place, issue definitely closed as not related to the image though.
