### ISSUE TITLE
SQLSTATE[HY000]: General error: 1 no such table: users

### ISSUE THREAD

**Issue by scifijunk** [linuxserver/docker-grocy#68]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I get the following error after doing a fresh install and trying to log in:

A server error occured while processing your request

If you think this is a bug, please report it
→ https://github.com/grocy/grocy/issues

Error source
/app/www/vendor/morris/lessql/src/LessQL/Database.php:108

Error message
SQLSTATE[HY000]: General error: 1 no such table: users

Stack trace
#0 /app/www/vendor/morris/lessql/src/LessQL/Database.php(108): PDO->prepare()
#1 /app/www/vendor/morris/lessql/src/LessQL/Database.php(491): LessQL\Database->prepare()
#2 /app/www/vendor/morris/lessql/src/LessQL/Result.php(143): LessQL\Database->select()
#3 /app/www/vendor/morris/lessql/src/LessQL/Result.php(322): LessQL\Result->execute()
#4 /app/www/middleware/DefaultAuthMiddleware.php(34): LessQL\Result->fetch()
#5 /app/www/controllers/LoginController.php(23): Grocy\Middleware\DefaultAuthMiddleware::ProcessLogin()
#6 /app/www/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(38): Grocy\Controllers\LoginController->ProcessLogin()
#7 /app/www/vendor/slim/slim/Slim/Routing/Route.php(358): Slim\Handlers\Strategies\RequestResponse->__invoke()
#8 /app/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\Routing\Route->handle()
#9 /app/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\MiddlewareDispatcher->handle()
#10 /app/www/vendor/slim/slim/Slim/Routing/Route.php(315): Slim\MiddlewareDispatcher->handle()
#11 /app/www/vendor/slim/slim/Slim/Routing/RouteRunner.php(68): Slim\Routing\Route->run()
#12 /app/www/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle()
#13 /app/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\LocaleMiddleware->__invoke()
#14 /app/www/middleware/AuthMiddleware.php(36): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#15 /app/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\AuthMiddleware->__invoke()
#16 /app/www/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(45): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#17 /app/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\RoutingMiddleware->process()
#18 /app/www/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#19 /app/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\ErrorMiddleware->process()
#20 /app/www/middleware/CorsMiddleware.php(30): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#21 /app/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\CorsMiddleware->__invoke()
#22 /app/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#23 /app/www/vendor/slim/slim/Slim/App.php(199): Slim\MiddlewareDispatcher->handle()
#24 /app/www/vendor/slim/slim/Slim/App.php(183): Slim\App->handle()
#25 /app/www/app.php(106): Slim\App->run()
#26 /app/www/public/index.php(45): require_once('...')
#27 {main}

Easy error info copy & paste (for reporting)
Error source:
```
/app/www/vendor/morris/lessql/src/LessQL/Database.php:108
```

Error message:
```
SQLSTATE[HY000]: General error: 1 no such table: users
```

Stack trace:
```
#0 /app/www/vendor/morris/lessql/src/LessQL/Database.php(108): PDO->prepare()
#1 /app/www/vendor/morris/lessql/src/LessQL/Database.php(491): LessQL\Database->prepare()
#2 /app/www/vendor/morris/lessql/src/LessQL/Result.php(143): LessQL\Database->select()
#3 /app/www/vendor/morris/lessql/src/LessQL/Result.php(322): LessQL\Result->execute()
#4 /app/www/middleware/DefaultAuthMiddleware.php(34): LessQL\Result->fetch()
#5 /app/www/controllers/LoginController.php(23): Grocy\Middleware\DefaultAuthMiddleware::ProcessLogin()
#6 /app/www/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(38): Grocy\Controllers\LoginController->ProcessLogin()
#7 /app/www/vendor/slim/slim/Slim/Routing/Route.php(358): Slim\Handlers\Strategies\RequestResponse->__invoke()
#8 /app/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\Routing\Route->handle()
#9 /app/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\MiddlewareDispatcher->handle()
#10 /app/www/vendor/slim/slim/Slim/Routing/Route.php(315): Slim\MiddlewareDispatcher->handle()
#11 /app/www/vendor/slim/slim/Slim/Routing/RouteRunner.php(68): Slim\Routing\Route->run()
#12 /app/www/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle()
#13 /app/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\LocaleMiddleware->__invoke()
#14 /app/www/middleware/AuthMiddleware.php(36): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#15 /app/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\AuthMiddleware->__invoke()
#16 /app/www/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(45): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#17 /app/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\RoutingMiddleware->process()
#18 /app/www/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#19 /app/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\ErrorMiddleware->process()
#20 /app/www/middleware/CorsMiddleware.php(30): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#21 /app/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\CorsMiddleware->__invoke()
#22 /app/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#23 /app/www/vendor/slim/slim/Slim/App.php(199): Slim\MiddlewareDispatcher->handle()
#24 /app/www/vendor/slim/slim/Slim/App.php(183): Slim\App->handle()
#25 /app/www/app.php(106): Slim\App->run()
#26 /app/www/public/index.php(45): require_once('...')
#27 {main}
```

System info:
```
{
    "grocy_version": {
        "Version": "3.3.2",
        "ReleaseDate": "2022-11-12"
    },
    "php_version": "8.2.7",
    "sqlite_version": "3.41.2",
    "os": "Linux 5.15.0-73-generic #80-Ubuntu SMP Mon May 15 15:18:26 UTC 2023 x86_64",
    "client": "Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/114.0.0.0 Safari\/537.36"
}
```

### Expected Behavior

For it to allow me to log in and start inputting data.

### Steps To Reproduce

1. Deleted Persisted folder
2. Created a new Persisted folder
3. Redeployed the Container with the latest tag

### Environment

```markdown
- OS: Ubuntu 22.04.2 LTS (GNU/Linux 5.15.0-73-generic x86_64)
- How docker service was installed: filling out the form in Portainer that is used as the GUI for my k3s cluster
```

### CPU architecture

x86-64

### Docker creation

```bash
Name: grocy
Namespace: household-management
Application Type: Deployment
Creation: scifijunkie 2022-02-17 23:57:36 Deployed from application form

Configuration

Container: grocy

Environment variable

PGID: 1000
PUID: 1000
TZ: America/Chicago

Persisted folder

/config: grocy-515cacb7-3432-43d7-a73b-6236e3c72d2c

Image

lscr.io/linuxserver/grocy:latest
```

### Container logs

```bash
[migrations] started
[migrations] 01-nginx-site-confs-default: executing...
[migrations] 01-nginx-site-confs-default: succeeded
[migrations] 02-default-location: executing...
grep: /config/nginx/site-confs/default.conf: No such file or directory
[migrations] 02-default-location: succeeded
[migrations] done
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 
   Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1000
User GID:    1000
───────────────────────────────────────
Setting resolver to  10.43.0.10
Setting worker_processes to 4
generating self-signed keys in /config/keys, you can replace these with your own keys if required
.+...+...+...............+....+..................+......+..+....+.........+.....+++++++++++++++++++++++++++++++++++++++*.............+...+................+++++++++++++++++++++++++++++++++++++++*....................+.................+....+...+..+.+...+.....+..........+.........+.....+.............++++++
.+......+++++++++++++++++++++++++++++++++++++++*.........+......+......+.........+....+..............+.+..+++++++++++++++++++++++++++++++++++++++*....+........+.......+........+...+.+.........+..+....+..............+.......+..+.+.....+.......+............+...+..............+.+..+...+.......+.....+...+...+.+........+.+.....+.+...+...+.........+......+....................+....+...+..+....+.................+............+...+............+......+......+...+.+...............+......+.....+...+...+...++++++
-----
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by TurnrDev** [comment]
Apparently you're meant to visit the `/` page https://github.com/grocy/grocy/issues/2284#issuecomment-1657758857

How are you getting logs? I am consistently unable to get any logs out of grocy :(

**Comment by j0nnymoe** [comment]
Clicking on the logo will remove the error as mentioned here: https://github.com/grocy/grocy/issues/2288
