### ISSUE TITLE
[BUG] Update from latest 3 to latest 4 breaks sql statements

### ISSUE THREAD

**Issue by ottes** [linuxserver/docker-grocy#74]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

no such table: cache quantity unit conversions resolved (View: /app/www/views/shoppinglist.blade.php)

after updating the docker-image, i guess there are missing db migrations that should have been done?
a downgrade to 4.0.0 also does not help, i'm stuck at the latest 3.

log of container looks good, i guess

### Expected Behavior

DB migrations and then a running 4.x

### Steps To Reproduce

1. install latest 3
2. insert some data
3. update to latest
4. see browser

### Environment

```markdown
- OS: Ubuntu
- How docker service was installed: like it should (i'm working with this since years, earning my money)
```

### CPU architecture

x86-64

### Docker creation

```bash
grocy:
    image: lscr.io/linuxserver/grocy:3.3.2  # ^-- set latest here to fail
    container_name: grocy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./docker/grocy/config:/config
    restart: unless-stopped
```

### Container logs

```bash
grocy           | [migrations] started
grocy           | [migrations] 01-nginx-site-confs-default: skipped
grocy           | [migrations] 02-default-location: skipped
grocy           | [migrations] done
grocy           | ───────────────────────────────────────
grocy           |
grocy           |       ██╗     ███████╗██╗ ██████╗
grocy           |       ██║     ██╔════╝██║██╔═══██╗
grocy           |       ██║     ███████╗██║██║   ██║
grocy           |       ██║     ╚════██║██║██║   ██║
grocy           |       ███████╗███████║██║╚██████╔╝
grocy           |       ╚══════╝╚══════╝╚═╝ ╚═════╝
grocy           |
grocy           |    Brought to you by linuxserver.io
grocy           | ───────────────────────────────────────
grocy           |
grocy           | To support LSIO projects visit:
grocy           | https://www.linuxserver.io/donate/
grocy           |
grocy           | ───────────────────────────────────────
grocy           | GID/UID
grocy           | ───────────────────────────────────────
grocy           |
grocy           | User UID:    1000
grocy           | User GID:    1000
grocy           | ───────────────────────────────────────
grocy           |
grocy           | using keys found in /config/keys
grocy           | **** The following active confs have different version dates than the samples that are shipped. ****
grocy           | **** This may be due to user customization or an update to the samples. ****
grocy           | **** You should compare the following files to the samples in the same folder and update them. ****
grocy           | **** Use the link at the top of the file to view the changelog. ****
grocy           | ┌────────────┬────────────┬────────────────────────────────────────────────────────────────────────┐
grocy           | │  old date  │  new date  │ path                                                                   │
grocy           | ├────────────┼────────────┼────────────────────────────────────────────────────────────────────────┤
grocy           | │ 2023-06-24 │ 2023-08-13 │ /config/nginx/ssl.conf                                                 │
grocy           | └────────────┴────────────┴────────────────────────────────────────────────────────────────────────┘
grocy           | [custom-init] No custom files found, skipping...
grocy           | [ls.io-init] done.
```

**Comment by berrnd** [comment]
> i guess there are missing db migrations that should have been done?

Since ever, Grocy's database migrations are executed when visiting the root route (`/`, simply click the logo on the left upper edge if you maybe only access a specific page because your bookmark points to that or whatever) - have you done that?

Grocy README ref: https://github.com/grocy/grocy#how-to-update

@ maintainers of this: Maybe make the DB migration hint more visible in your README or at another appropriate place, this here is the 84th (or so) report of that kind since the v4.0.0 release...

**Comment by thespad** [comment]
> > i guess there are missing db migrations that should have been done?
> 
> Since ever, Grocy's database migrations are executed when visiting the root route (`/`, simply click the logo on the left upper edge if you maybe only access a specific page because your bookmark points to that or whatever) - have you done that?
> 
> Grocy README ref: [grocy/grocy#how-to-update](https://github.com/grocy/grocy#how-to-update)
> 
> @ maintainers of this: Maybe make the DB migration hint more visible in your README or at another appropriate place, this here is the 84th (or so) report of that kind since the v4.0.0 release...

https://github.com/linuxserver/docker-grocy/pull/75 though on past experience very few will actually read it...
