### ISSUE TITLE
[BUG] "Compatibility Issues" when using linuxserver.io v4.2.0 image with Android app

### ISSUE THREAD

**Issue by kmanwar89** [linuxserver/docker-grocy#89]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Attempting to sign the Grocy app from the Google Play store on an Android smartphone yields a "compatibility issues" error message stating 4.2.0 is not compatible - 4.0.0,0.1,0.2,0.3 and 4.1.0 are listed as supported server versions.

### Expected Behavior

Multiple image versions should be available as the official repository for grocy/grocy-docker is no longer maintained, so there are no other options for Docker images.

### Steps To Reproduce

1. Spin up a grocy server instance using the :latest image tag
2. Install the grocy app from the Google Play store on an Android smartphone
3. Select "own server" and scan the API key QR code from another device
4. Error message will appear

### Environment

```markdown
- OS: Ubuntu Server 24.04 LTS
- How docker service was installed: Docker compose file from [Linuxserver.io Github page](https://github.com/linuxserver/docker-grocy?tab=readme-ov-file#docker-compose-recommended-click-here-for-more-info)
```

### CPU architecture

x86-64

### Docker creation

```bash
---
name: grocy
services:
  grocy:
    container_name: grocy
    image: lscr.io/linuxserver/grocy:latest
    restart: always
    volumes:
      - ./config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    networks:
      - services

networks:
  services:
    name: services
    external: true
```

### Container logs

```bash
[migrations] started
[migrations] 01-nginx-site-confs-default: executing...
[migrations] 01-nginx-site-confs-default: succeeded
[migrations] 02-default-location: executing...
[migrations] 02-default-location: succeeded
[migrations] done
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────
Linuxserver.io version: v4.2.0-ls258
Build-date: 2024-07-19T21:37:21+00:00
───────────────────────────────────────

Setting resolver to  127.0.0.11
Setting worker_processes to 8
generating self-signed keys in /config/keys, you can replace these with your own keys if required
.........+.....+++++++++++++++++++++++++++++++++++++++*.........+++++++++++++++++++++++++++++++++++++++*......+............+.........+.+.................+.+............+..+.+.....+....+...+...+...........+.+.....+....+.....+...+...+.......+......+.....+..........+..+...............++++++
........+..+...................+++++++++++++++++++++++++++++++++++++++*.+..+.......+..+.........+..........+.....+++++++++++++++++++++++++++++++++++++++*..........+..+..........+.........+..+...+.........+...+....+.........+..+.......+..+.+..+.+.........+.....+......+.+...........+..........+...+...............+..+...+.+.....+...+...+...+...............+.......+.....+............+.+.........+.....++++++
-----
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by kmanwar89** [comment]
![Screenshot_20240721_190346_Grocy](https://github.com/user-attachments/assets/afcb8516-9fd1-4c1e-a7e8-2c4ec6cc5bf0)

**Comment by j0nnymoe** [comment]
You can pin to the version of grocy that you need via the tags. Though it would be better just for the android app to update for support of the newer versions.

**Comment by thespad** [comment]
All of the previous tags are available to be pulled https://hub.docker.com/r/linuxserver/grocy/tags, though as 4.2.0 was released back in March you might want to find a better app.

**Comment by kmanwar89** [comment]
Wow, that was fast!

Fully recognize you aren't the developers of the app, but it seems to me there is a disconnect somewhere between the version numbers. It looks like the app developers have a GitHub page, so I may raise the issue over there.

I did check linuxserver.io and search for Grocy, but did not see any tags other than 4.2.0 - I didn't think the Docker hub would be a more updated source of information. Is it possible to have the LinuxServer UI updated to reflect all available tags for exactly this purpose?

**Comment by thespad** [comment]
There are literally hundreds, sometimes thousands, of tags for most of our images, listing them all other than on the registries would be impractical.

We just package Grocy, we have no control over when they release versions, or indeed when 3rd party mobile app developers bother to update to support them.
