### ISSUE TITLE
Docker updated to newest version of grocy causing data loss

### ISSUE THREAD

**Issue by tony4212** [linuxserver/docker-grocy#9]
After watchtower updated grocy docker I notice that all the data in it was missing. I don't know if this is a problem with how this docker is set up or how watchtower updated.

**Comment by thelamer** [comment]
Please post your container logs and run command for this container. 

I cannot replicate this locally. 

Also please elaborate on what you mean by data loss. 

Thanks!

**Comment by CHBMB** [comment]
No response to request for information.  Closing as only report we've had of this.
