### ISSUE TITLE
[FEAT] Support Linux/arm/v7 for Raspberry Pi

### ISSUE THREAD

**Issue by atharvai** [linuxserver/docker-grocy#91]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Currently the docker image doesn't have manifest for the Linux/arm/v7 platform. This is common for raspberry pi devices. 

### Reason for change

Raspberry pi is common platform to run such services on.

**Comment by Roxedus** [comment]
We removed armhf support over a year ago, as 32bit only devices has not really been a thing for years. For perspective, a pi 3 has a 64bit cpu, and can therefore run 64bit OS'.

https://www.linuxserver.io/blog/a-farewell-to-arm-hf
